version: '3'

services:
  postgresql:
    image: postgres
    container_name: mushunter
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=mushunter
      - POSTGRES_PASSWORD=mushunter
      - POSTGRES_DATABASE=mushunter
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'